language: go
sudo: false
go_import_path: github.com/kindevil/periph
go:
    # Dear future me: if you touch this line, don't forget to update the
    # conditions below!
  - 1.7.6
  - 1.12.1

before_script:
  - echo $TRAVIS_GO_VERSION
  - go get -t -v github.com/kindevil/periph/...
script:
  # Checks run everywhere.
  - if find . -path ./.git -prune -o -type f -executable -print | grep -e . ; then echo 'Do not commit executables'; false; fi
  # Checks run only on the latest version.
  - if [[ $TRAVIS_GO_VERSION != 1.7.6 ]]; then echo 'Check Code is well formatted'; ! gofmt -s -d . | read; fi
  - if [[ $TRAVIS_GO_VERSION != 1.7.6 ]]; then echo 'Looking for external dependencies:'; go list -f '{{join .Imports "\n"}}' github.com/kindevil/periph/... | sort | uniq | grep -v ^github.com/kindevil/periph | xargs go list -f '{{if not .Standard}}- {{.ImportPath}}{{end}}'; fi
  - if [[ $TRAVIS_GO_VERSION != 1.7.6 ]]; then echo 'Erroring on external dependencies:'; ! go list -f '{{join .Imports "\n"}}' github.com/kindevil/periph/... | sort | uniq | grep -v ^github.com/kindevil/periph | xargs go list -f '{{if not .Standard}}Remove {{.ImportPath}}{{end}}' | grep -q Remove; fi
  - if [[ $TRAVIS_GO_VERSION != 1.7.6 ]]; then echo 'Erroring on /host depending on /devices:'; ! go list -f '{{.ImportPath}} depends on {{join .Imports ", "}}' github.com/kindevil/periph/host/... | sort | uniq | grep github.com/kindevil/periph/devices; fi
  - if [[ $TRAVIS_GO_VERSION != 1.7.6 ]]; then echo 'Erroring on /conn depending on /devices:'; ! go list -f '{{.ImportPath}} depends on {{join .Imports ", "}}' github.com/kindevil/periph/conn/... | sort | uniq | grep github.com/kindevil/periph/devices; fi
  - if [[ $TRAVIS_GO_VERSION != 1.7.6 ]]; then echo 'Erroring on /conn depending on /host:'; ! go list -f '{{.ImportPath}} depends on {{join .Imports ", "}}' github.com/kindevil/periph/conn/... | sort | uniq | grep github.com/kindevil/periph/host; fi
  - if [[ $TRAVIS_GO_VERSION != 1.7.6 ]]; then bash -c 'set -e; echo "" > coverage.txt; for d in $(go list ./...); do go test -covermode=count -coverprofile=p.out $d; if [ -f p.out ]; then cat p.out >> coverage.txt; rm p.out; fi; done'; fi
  - if [[ $TRAVIS_GO_VERSION != 1.7.6 ]]; then go test -race ./...; fi
  # Check run on older versions.
  - if [[ $TRAVIS_GO_VERSION == 1.7.6 ]]; then go test ./...; fi
after_success:
  - if [[ $TRAVIS_GO_VERSION != 1.7.6 ]]; then bash <(curl -s https://codecov.io/bash); fi
